version: "3.7"

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-metastore:

services:

  namenode:
    image: timveil/docker-hadoop-namenode:3.1.x
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hive-3.1.x
    env_file:
      - core.env
      - yarn-remote.env
    ports:
      - "9870:9870"

  datanode:
    image: timveil/docker-hadoop-datanode:3.1.x
    container_name: datanode
    hostname: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - core.env
      - yarn-remote.env
    ports:
      - "9864:9864"

  resourcemanager:
    image: timveil/docker-hadoop-resourcemanager:3.1.x
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864
    env_file:
      - core.env
      - yarn-resource-manager.env
    ports:
      - "8088:8088"

  nodemanager:
    image: timveil/docker-hadoop-nodemanager:3.1.x
    container_name: nodemanager
    hostname: nodemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    env_file:
      - core.env
      - yarn-node-manager.env
    ports:
      - "8042:8042"

  historyserver:
    image: timveil/docker-hadoop-historyserver:3.1.x
    container_name: historyserver
    hostname: historyserver
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 resourcemanager:8088
    env_file:
      - core.env
      - yarn-timeline.env
    ports:
      - "8188:8188"

  hs2:
    image: timveil/docker-hadoop-hive-hs2:3.1.x-fork
    container_name: hs2
    hostname: hs2
    environment:
      - SERVICE_PRECONDITION=metastore:9083
    env_file:
      - core.env
      - yarn-remote.env
      - hive.env
    ports:
      - "10000:10000"
      - "10002:10002"

  metastore:
    image: timveil/docker-hadoop-hive-metastore-standalone:3.1.x
    container_name: metastore
    hostname: metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 metastore-db:5432
    volumes:
      - certs-metastore:/certs
    env_file:
      - core.env
      - yarn-remote.env
      - metastore-standalone.env

##########################################################
# Cockroach DB
##########################################################
  metastore-db:
    container_name: metastore-db
    hostname: metastore-db
    image: timveil/dynamic-haproxy:latest
    ports:
      - "5432:5432"
      - "8080:8080"
      - "8081:8081"
    environment:
      - NODES=roach-0 roach-1 roach-2
      - HTTP_BIND_PORT=5432
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-metastore:/certs/metastore

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --certs-dir=/certs --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257
    volumes:
      - certs-roach-0:/certs
      - ${PWD}/sql:/cockroach/sql
    depends_on:
      - roach-cert

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --certs-dir=/certs --join=roach-0 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257
    volumes:
      - certs-roach-1:/certs
    depends_on:
      - roach-cert
      - roach-0

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --certs-dir=/certs --join=roach-0 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257
    volumes:
      - certs-roach-2:/certs
    depends_on:
      - roach-cert
      - roach-0



